stages:
    - test
    - lint

pre-commit:
    image: python:3.9
    stage: lint
    before_script:
        - which python3
        - which pip
        - pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
        - pip install pre-commit
        - pip install pylint
    variables:
        PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
    cache:
        paths:
            - ${PRE_COMMIT_HOME}
    script:
        - echo ${CI_COMMIT_SHA}
        - pre-commit run --from-ref ${CI_COMMIT_BEFORE_SHA} --to-ref ${CI_COMMIT_SHA}
#    only:
#        - merge_requests
